pages = [{"l":"index.html","n":"comet-api-docs","t":"comet-api-docs","d":"","k":"static"},
{"l":"buildinfo.html","n":"buildinfo","t":"package buildinfo","d":"buildinfo","k":"package"},
{"l":"buildinfo/BuildInfo$.html","n":"BuildInfo","t":"object BuildInfo","d":"buildinfo/BuildInfo$","k":"object"},
{"l":"buildinfo/BuildInfo$.html","n":"name","t":"val name: String","d":"buildinfo/BuildInfo$","k":"val"},
{"l":"buildinfo/BuildInfo$.html","n":"sbtVersion","t":"val sbtVersion: String","d":"buildinfo/BuildInfo$","k":"val"},
{"l":"buildinfo/BuildInfo$.html","n":"scalaVersion","t":"val scalaVersion: String","d":"buildinfo/BuildInfo$","k":"val"},
{"l":"buildinfo/BuildInfo$.html","n":"toString","t":"val toString: String","d":"buildinfo/BuildInfo$","k":"val"},
{"l":"buildinfo/BuildInfo$.html","n":"version","t":"val version: String","d":"buildinfo/BuildInfo$","k":"val"},
{"l":"org/ragna/comet.html","n":"org.ragna.comet","t":"package org.ragna.comet","d":"org/ragna/comet","k":"package"},
{"l":"org/ragna/comet/Main$.html","n":"Main","t":"object Main extends IOApp with LazyLogging","d":"org/ragna/comet/Main$","k":"object"},
{"l":"org/ragna/comet/data.html","n":"org.ragna.comet.data","t":"package org.ragna.comet.data","d":"org/ragna/comet/data","k":"package"},
{"l":"org/ragna/comet/data/DataFormat.html","n":"DataFormat","t":"class DataFormat(val name: String)","d":"org/ragna/comet/data/DataFormat","k":"class"},
{"l":"org/ragna/comet/data/DataFormat.html","n":"name","t":"val name: String","d":"org/ragna/comet/data/DataFormat","k":"val"},
{"l":"org/ragna/comet/data/DataFormat$.html","n":"DataFormat","t":"object DataFormat","d":"org/ragna/comet/data/DataFormat$","k":"object"},
{"l":"org/ragna/comet/data/DataFormat$$JSONLD$.html","n":"JSONLD","t":"object JSONLD extends DataFormat","d":"org/ragna/comet/data/DataFormat$$JSONLD$","k":"object"},
{"l":"org/ragna/comet/data/DataFormat$$NTRIPLES$.html","n":"NTRIPLES","t":"object NTRIPLES extends DataFormat","d":"org/ragna/comet/data/DataFormat$$NTRIPLES$","k":"object"},
{"l":"org/ragna/comet/data/DataFormat$$RDFJSON$.html","n":"RDFJSON","t":"object RDFJSON extends DataFormat","d":"org/ragna/comet/data/DataFormat$$RDFJSON$","k":"object"},
{"l":"org/ragna/comet/data/DataFormat$$RDFXML$.html","n":"RDFXML","t":"object RDFXML extends DataFormat","d":"org/ragna/comet/data/DataFormat$$RDFXML$","k":"object"},
{"l":"org/ragna/comet/data/DataFormat$$TRIG$.html","n":"TRIG","t":"object TRIG extends DataFormat","d":"org/ragna/comet/data/DataFormat$$TRIG$","k":"object"},
{"l":"org/ragna/comet/data/DataFormat$$TURTLE$.html","n":"TURTLE","t":"object TURTLE extends DataFormat","d":"org/ragna/comet/data/DataFormat$$TURTLE$","k":"object"},
{"l":"org/ragna/comet/exception/stream/timed.html","n":"org.ragna.comet.exception.stream.timed","t":"package org.ragna.comet.exception.stream.timed","d":"org/ragna/comet/exception/stream/timed","k":"package"},
{"l":"org/ragna/comet/exception/stream/timed/StreamTimeoutException.html","n":"StreamTimeoutException","t":"class StreamTimeoutException(timeoutInterval: Option[FiniteDuration]) extends RuntimeException","d":"org/ragna/comet/exception/stream/timed/StreamTimeoutException","k":"class"},
{"l":"org/ragna/comet/exception/stream/timed/StreamTimeoutException$.html","n":"StreamTimeoutException","t":"object StreamTimeoutException","d":"org/ragna/comet/exception/stream/timed/StreamTimeoutException$","k":"object"},
{"l":"org/ragna/comet/exception/stream/validations.html","n":"org.ragna.comet.exception.stream.validations","t":"package org.ragna.comet.exception.stream.validations","d":"org/ragna/comet/exception/stream/validations","k":"package"},
{"l":"org/ragna/comet/exception/stream/validations/StreamErroredItemException.html","n":"StreamErroredItemException","t":"class StreamErroredItemException(message: String, cause: Throwable) extends StreamValidationException","d":"org/ragna/comet/exception/stream/validations/StreamErroredItemException","k":"class"},
{"l":"org/ragna/comet/exception/stream/validations/StreamErroredItemException$.html","n":"StreamErroredItemException","t":"object StreamErroredItemException","d":"org/ragna/comet/exception/stream/validations/StreamErroredItemException$","k":"object"},
{"l":"org/ragna/comet/exception/stream/validations/StreamErroredItemException$.html","n":"apply","t":"def apply(message: String, cause: Option[Throwable]): StreamErroredItemException","d":"org/ragna/comet/exception/stream/validations/StreamErroredItemException$","k":"def"},
{"l":"org/ragna/comet/exception/stream/validations/StreamErroredItemException$.html","n":"prefix","t":"val prefix: String","d":"org/ragna/comet/exception/stream/validations/StreamErroredItemException$","k":"val"},
{"l":"org/ragna/comet/exception/stream/validations/StreamInvalidItemException.html","n":"StreamInvalidItemException","t":"class StreamInvalidItemException(message: String, cause: Throwable, reason: Option[Result]) extends StreamValidationException","d":"org/ragna/comet/exception/stream/validations/StreamInvalidItemException","k":"class"},
{"l":"org/ragna/comet/exception/stream/validations/StreamInvalidItemException$.html","n":"StreamInvalidItemException","t":"object StreamInvalidItemException","d":"org/ragna/comet/exception/stream/validations/StreamInvalidItemException$","k":"object"},
{"l":"org/ragna/comet/exception/stream/validations/StreamInvalidItemException$.html","n":"apply","t":"def apply(message: String, cause: Option[Throwable], reason: Option[Result]): StreamInvalidItemException","d":"org/ragna/comet/exception/stream/validations/StreamInvalidItemException$","k":"def"},
{"l":"org/ragna/comet/exception/stream/validations/StreamInvalidItemException$.html","n":"prefix","t":"val prefix: String","d":"org/ragna/comet/exception/stream/validations/StreamInvalidItemException$","k":"val"},
{"l":"org/ragna/comet/exception/stream/validations/StreamValidationException.html","n":"StreamValidationException","t":"class StreamValidationException(val message: String, val cause: Throwable, val status: ResultStatus, val reason: Option[Result]) extends Exception","d":"org/ragna/comet/exception/stream/validations/StreamValidationException","k":"class"},
{"l":"org/ragna/comet/exception/stream/validations/StreamValidationException.html","n":"cause","t":"val cause: Throwable","d":"org/ragna/comet/exception/stream/validations/StreamValidationException","k":"val"},
{"l":"org/ragna/comet/exception/stream/validations/StreamValidationException.html","n":"message","t":"val message: String","d":"org/ragna/comet/exception/stream/validations/StreamValidationException","k":"val"},
{"l":"org/ragna/comet/exception/stream/validations/StreamValidationException.html","n":"reason","t":"val reason: Option[Result]","d":"org/ragna/comet/exception/stream/validations/StreamValidationException","k":"val"},
{"l":"org/ragna/comet/exception/stream/validations/StreamValidationException.html","n":"status","t":"val status: ResultStatus","d":"org/ragna/comet/exception/stream/validations/StreamValidationException","k":"val"},
{"l":"org/ragna/comet/exception/stream/validations/StreamValidationException$.html","n":"StreamValidationException","t":"object StreamValidationException","d":"org/ragna/comet/exception/stream/validations/StreamValidationException$","k":"object"},
{"l":"org/ragna/comet/implicits.html","n":"org.ragna.comet.implicits","t":"package org.ragna.comet.implicits","d":"org/ragna/comet/implicits","k":"package"},
{"l":"org/ragna/comet/implicits/RDFElementImplicits$.html","n":"RDFElementImplicits","t":"object RDFElementImplicits","d":"org/ragna/comet/implicits/RDFElementImplicits$","k":"object"},
{"l":"org/ragna/comet/implicits/RDFElementImplicits$.html","n":"rdfFromString","t":"def rdfFromString(input: String): RDFElement","d":"org/ragna/comet/implicits/RDFElementImplicits$","k":"def"},
{"l":"org/ragna/comet/model/rdf.html","n":"org.ragna.comet.model.rdf","t":"package org.ragna.comet.model.rdf","d":"org/ragna/comet/model/rdf","k":"package"},
{"l":"org/ragna/comet/model/rdf/RDFElement.html","n":"RDFElement","t":"class RDFElement(rdf: String)","d":"org/ragna/comet/model/rdf/RDFElement","k":"class"},
{"l":"org/ragna/comet/model/rdf/RDFElement.html","n":"content","t":"val content: String","d":"org/ragna/comet/model/rdf/RDFElement","k":"val"},
{"l":"org/ragna/comet/model/rdf/RDFElement$.html","n":"RDFElement","t":"object RDFElement","d":"org/ragna/comet/model/rdf/RDFElement$","k":"object"},
{"l":"org/ragna/comet/model/rdf/RDFElement$.html","n":"apply","t":"def apply(inputRdf: String): RDFElement","d":"org/ragna/comet/model/rdf/RDFElement$","k":"def"},
{"l":"org/ragna/comet/schema.html","n":"org.ragna.comet.schema","t":"package org.ragna.comet.schema","d":"org/ragna/comet/schema","k":"package"},
{"l":"org/ragna/comet/schema/ShExSchemaFormat.html","n":"ShExSchemaFormat","t":"class ShExSchemaFormat(val name: String)","d":"org/ragna/comet/schema/ShExSchemaFormat","k":"class"},
{"l":"org/ragna/comet/schema/ShExSchemaFormat.html","n":"name","t":"val name: String","d":"org/ragna/comet/schema/ShExSchemaFormat","k":"val"},
{"l":"org/ragna/comet/schema/ShExSchemaFormat$.html","n":"ShExSchemaFormat","t":"object ShExSchemaFormat","d":"org/ragna/comet/schema/ShExSchemaFormat$","k":"object"},
{"l":"org/ragna/comet/schema/ShExSchemaFormat$$SHEXC$.html","n":"SHEXC","t":"object SHEXC extends ShExSchemaFormat","d":"org/ragna/comet/schema/ShExSchemaFormat$$SHEXC$","k":"object"},
{"l":"org/ragna/comet/schema/ShExSchemaFormat$$SHEXJ$.html","n":"SHEXJ","t":"object SHEXJ extends ShExSchemaFormat","d":"org/ragna/comet/schema/ShExSchemaFormat$$SHEXJ$","k":"object"},
{"l":"org/ragna/comet/stream.html","n":"org.ragna.comet.stream","t":"package org.ragna.comet.stream","d":"org/ragna/comet/stream","k":"package"},
{"l":"org/ragna/comet/stream/StreamSource.html","n":"StreamSource","t":"class StreamSource(val name: String)","d":"org/ragna/comet/stream/StreamSource","k":"class"},
{"l":"org/ragna/comet/stream/StreamSource.html","n":"name","t":"val name: String","d":"org/ragna/comet/stream/StreamSource","k":"val"},
{"l":"org/ragna/comet/stream/StreamSource$.html","n":"StreamSource","t":"object StreamSource","d":"org/ragna/comet/stream/StreamSource$","k":"object"},
{"l":"org/ragna/comet/stream/StreamSource$$Files$.html","n":"Files","t":"object Files extends StreamSource","d":"org/ragna/comet/stream/StreamSource$$Files$","k":"object"},
{"l":"org/ragna/comet/stream/StreamSource$$Kafka$.html","n":"Kafka","t":"object Kafka extends StreamSource","d":"org/ragna/comet/stream/StreamSource$$Kafka$","k":"object"},
{"l":"org/ragna/comet/stream/StreamSource$$List$.html","n":"List","t":"object List extends StreamSource","d":"org/ragna/comet/stream/StreamSource$$List$","k":"object"},
{"l":"org/ragna/comet/stream/extractors.html","n":"org.ragna.comet.stream.extractors","t":"package org.ragna.comet.stream.extractors","d":"org/ragna/comet/stream/extractors","k":"package"},
{"l":"org/ragna/comet/stream/extractors/StreamExtractor.html","n":"StreamExtractor","t":"class StreamExtractor[A](val format: DataFormat, val inference: InferenceEngine, val concurrentItems: Int, val itemTimeout: Option[FiniteDuration])(implicit toRdfElement: A => RDFElement)","d":"org/ragna/comet/stream/extractors/StreamExtractor","k":"class"},
{"l":"org/ragna/comet/stream/extractors/StreamExtractor.html","n":"dataStream","t":"val dataStream: Stream[IO, RDFValidationItem]","d":"org/ragna/comet/stream/extractors/StreamExtractor","k":"val"},
{"l":"org/ragna/comet/stream/extractors/StreamExtractor.html","n":"format","t":"val format: DataFormat","d":"org/ragna/comet/stream/extractors/StreamExtractor","k":"val"},
{"l":"org/ragna/comet/stream/extractors/StreamExtractor.html","n":"inference","t":"val inference: InferenceEngine","d":"org/ragna/comet/stream/extractors/StreamExtractor","k":"val"},
{"l":"org/ragna/comet/stream/extractors/StreamExtractor.html","n":"source","t":"val source: StreamSource","d":"org/ragna/comet/stream/extractors/StreamExtractor","k":"val"},
{"l":"org/ragna/comet/stream/extractors/StreamExtractor$.html","n":"StreamExtractor","t":"object StreamExtractor","d":"org/ragna/comet/stream/extractors/StreamExtractor$","k":"object"},
{"l":"org/ragna/comet/stream/extractors/StreamExtractor$$Defaults$.html","n":"Defaults","t":"object Defaults","d":"org/ragna/comet/stream/extractors/StreamExtractor$$Defaults$","k":"object"},
{"l":"org/ragna/comet/stream/extractors/StreamExtractor$$Defaults$.html","n":"defaultConcurrentParsing","t":"val defaultConcurrentParsing: Int","d":"org/ragna/comet/stream/extractors/StreamExtractor$$Defaults$","k":"val"},
{"l":"org/ragna/comet/stream/extractors/StreamExtractor$$Defaults$.html","n":"defaultIncomingItemsTimeout","t":"val defaultIncomingItemsTimeout: Option[FiniteDuration]","d":"org/ragna/comet/stream/extractors/StreamExtractor$$Defaults$","k":"val"},
{"l":"org/ragna/comet/stream/extractors/StreamExtractor$$Defaults$.html","n":"defaultInferenceEngine","t":"val defaultInferenceEngine: InferenceEngine","d":"org/ragna/comet/stream/extractors/StreamExtractor$$Defaults$","k":"val"},
{"l":"org/ragna/comet/stream/extractors/file.html","n":"org.ragna.comet.stream.extractors.file","t":"package org.ragna.comet.stream.extractors.file","d":"org/ragna/comet/stream/extractors/file","k":"package"},
{"l":"org/ragna/comet/stream/extractors/file/Charsets.html","n":"Charsets","t":"class Charsets(val value: Charset)","d":"org/ragna/comet/stream/extractors/file/Charsets","k":"class"},
{"l":"org/ragna/comet/stream/extractors/file/Charsets.html","n":"value","t":"val value: Charset","d":"org/ragna/comet/stream/extractors/file/Charsets","k":"val"},
{"l":"org/ragna/comet/stream/extractors/file/Charsets$.html","n":"Charsets","t":"object Charsets","d":"org/ragna/comet/stream/extractors/file/Charsets$","k":"object"},
{"l":"org/ragna/comet/stream/extractors/file/Charsets$$ASCII$.html","n":"ASCII","t":"object ASCII extends Charsets","d":"org/ragna/comet/stream/extractors/file/Charsets$$ASCII$","k":"object"},
{"l":"org/ragna/comet/stream/extractors/file/Charsets$$ISO_8859_1$.html","n":"ISO_8859_1","t":"object ISO_8859_1 extends Charsets","d":"org/ragna/comet/stream/extractors/file/Charsets$$ISO_8859_1$","k":"object"},
{"l":"org/ragna/comet/stream/extractors/file/Charsets$$UTF16$.html","n":"UTF16","t":"object UTF16 extends Charsets","d":"org/ragna/comet/stream/extractors/file/Charsets$$UTF16$","k":"object"},
{"l":"org/ragna/comet/stream/extractors/file/Charsets$$UTF32$.html","n":"UTF32","t":"object UTF32 extends Charsets","d":"org/ragna/comet/stream/extractors/file/Charsets$$UTF32$","k":"object"},
{"l":"org/ragna/comet/stream/extractors/file/Charsets$$UTF8$.html","n":"UTF8","t":"object UTF8 extends Charsets","d":"org/ragna/comet/stream/extractors/file/Charsets$$UTF8$","k":"object"},
{"l":"org/ragna/comet/stream/extractors/file/FileExtractor.html","n":"FileExtractor","t":"class FileExtractor(files: Seq[Path], charset: Charset, format: DataFormat, inference: InferenceEngine, concurrentItems: Int, itemTimeout: Option[FiniteDuration]) extends StreamExtractor[String]","d":"org/ragna/comet/stream/extractors/file/FileExtractor","k":"class"},
{"l":"org/ragna/comet/stream/extractors/file/FileExtractor.html","n":"source","t":"val source: StreamSource","d":"org/ragna/comet/stream/extractors/file/FileExtractor","k":"val"},
{"l":"org/ragna/comet/stream/extractors/file/FileExtractor$.html","n":"FileExtractor","t":"object FileExtractor","d":"org/ragna/comet/stream/extractors/file/FileExtractor$","k":"object"},
{"l":"org/ragna/comet/stream/extractors/file/FileExtractor$$Defaults$.html","n":"Defaults","t":"object Defaults","d":"org/ragna/comet/stream/extractors/file/FileExtractor$$Defaults$","k":"object"},
{"l":"org/ragna/comet/stream/extractors/file/FileExtractor$$Defaults$.html","n":"defaultCharset","t":"val defaultCharset: Charset","d":"org/ragna/comet/stream/extractors/file/FileExtractor$$Defaults$","k":"val"},
{"l":"org/ragna/comet/stream/extractors/kafka.html","n":"org.ragna.comet.stream.extractors.kafka","t":"package org.ragna.comet.stream.extractors.kafka","d":"org/ragna/comet/stream/extractors/kafka","k":"package"},
{"l":"org/ragna/comet/stream/extractors/kafka/KafkaExtractor.html","n":"KafkaExtractor","t":"class KafkaExtractor[K, V](configuration: KafkaExtractorConfiguration, format: DataFormat, inference: InferenceEngine, concurrentItems: Int, itemTimeout: Option[FiniteDuration])(implicit keyDeserializer: Deserializer[IO, K], valueDeserializer: Deserializer[IO, V], toRdfElement: V => RDFElement) extends StreamExtractor[V]","d":"org/ragna/comet/stream/extractors/kafka/KafkaExtractor","k":"class"},
{"l":"org/ragna/comet/stream/extractors/kafka/KafkaExtractor.html","n":"source","t":"val source: StreamSource","d":"org/ragna/comet/stream/extractors/kafka/KafkaExtractor","k":"val"},
{"l":"org/ragna/comet/stream/extractors/kafka/KafkaExtractor$.html","n":"KafkaExtractor","t":"object KafkaExtractor","d":"org/ragna/comet/stream/extractors/kafka/KafkaExtractor$","k":"object"},
{"l":"org/ragna/comet/stream/extractors/kafka/KafkaExtractorConfiguration.html","n":"KafkaExtractorConfiguration","t":"class KafkaExtractorConfiguration(topic: String, server: String, port: Int, groupId: String, offsetReset: AutoOffsetReset, autoCommit: Boolean, sessionTimeout: FiniteDuration, commitRecovery: CommitRecovery, commitTimeout: FiniteDuration, commitInterval: FiniteDuration, pollTimeout: FiniteDuration, pollInterval: FiniteDuration, concurrentItems: Int)","d":"org/ragna/comet/stream/extractors/kafka/KafkaExtractorConfiguration","k":"class"},
{"l":"org/ragna/comet/stream/extractors/kafka/KafkaExtractorConfiguration.html","n":"bootstrapServers","t":"val bootstrapServers: String","d":"org/ragna/comet/stream/extractors/kafka/KafkaExtractorConfiguration","k":"val"},
{"l":"org/ragna/comet/stream/extractors/kafka/KafkaExtractorConfiguration$.html","n":"KafkaExtractorConfiguration","t":"object KafkaExtractorConfiguration","d":"org/ragna/comet/stream/extractors/kafka/KafkaExtractorConfiguration$","k":"object"},
{"l":"org/ragna/comet/stream/extractors/kafka/KafkaExtractorConfiguration$$Defaults$.html","n":"Defaults","t":"object Defaults","d":"org/ragna/comet/stream/extractors/kafka/KafkaExtractorConfiguration$$Defaults$","k":"object"},
{"l":"org/ragna/comet/stream/extractors/kafka/KafkaExtractorConfiguration$$Defaults$.html","n":"defaultAutoCommit","t":"val defaultAutoCommit: Boolean","d":"org/ragna/comet/stream/extractors/kafka/KafkaExtractorConfiguration$$Defaults$","k":"val"},
{"l":"org/ragna/comet/stream/extractors/kafka/KafkaExtractorConfiguration$$Defaults$.html","n":"defaultCommitInterval","t":"val defaultCommitInterval: FiniteDuration","d":"org/ragna/comet/stream/extractors/kafka/KafkaExtractorConfiguration$$Defaults$","k":"val"},
{"l":"org/ragna/comet/stream/extractors/kafka/KafkaExtractorConfiguration$$Defaults$.html","n":"defaultCommitRecovery","t":"val defaultCommitRecovery: CommitRecovery","d":"org/ragna/comet/stream/extractors/kafka/KafkaExtractorConfiguration$$Defaults$","k":"val"},
{"l":"org/ragna/comet/stream/extractors/kafka/KafkaExtractorConfiguration$$Defaults$.html","n":"defaultCommitTimeout","t":"val defaultCommitTimeout: FiniteDuration","d":"org/ragna/comet/stream/extractors/kafka/KafkaExtractorConfiguration$$Defaults$","k":"val"},
{"l":"org/ragna/comet/stream/extractors/kafka/KafkaExtractorConfiguration$$Defaults$.html","n":"defaultConcurrentEvaluations","t":"val defaultConcurrentEvaluations: Int","d":"org/ragna/comet/stream/extractors/kafka/KafkaExtractorConfiguration$$Defaults$","k":"val"},
{"l":"org/ragna/comet/stream/extractors/kafka/KafkaExtractorConfiguration$$Defaults$.html","n":"defaultConsumerGroupId","t":"val defaultConsumerGroupId: String","d":"org/ragna/comet/stream/extractors/kafka/KafkaExtractorConfiguration$$Defaults$","k":"val"},
{"l":"org/ragna/comet/stream/extractors/kafka/KafkaExtractorConfiguration$$Defaults$.html","n":"defaultOffsetResetStrategy","t":"val defaultOffsetResetStrategy: AutoOffsetReset","d":"org/ragna/comet/stream/extractors/kafka/KafkaExtractorConfiguration$$Defaults$","k":"val"},
{"l":"org/ragna/comet/stream/extractors/kafka/KafkaExtractorConfiguration$$Defaults$.html","n":"defaultPollInterval","t":"val defaultPollInterval: FiniteDuration","d":"org/ragna/comet/stream/extractors/kafka/KafkaExtractorConfiguration$$Defaults$","k":"val"},
{"l":"org/ragna/comet/stream/extractors/kafka/KafkaExtractorConfiguration$$Defaults$.html","n":"defaultPollTimeout","t":"val defaultPollTimeout: FiniteDuration","d":"org/ragna/comet/stream/extractors/kafka/KafkaExtractorConfiguration$$Defaults$","k":"val"},
{"l":"org/ragna/comet/stream/extractors/kafka/KafkaExtractorConfiguration$$Defaults$.html","n":"defaultServerLocation","t":"val defaultServerLocation: String","d":"org/ragna/comet/stream/extractors/kafka/KafkaExtractorConfiguration$$Defaults$","k":"val"},
{"l":"org/ragna/comet/stream/extractors/kafka/KafkaExtractorConfiguration$$Defaults$.html","n":"defaultServerPort","t":"val defaultServerPort: Int","d":"org/ragna/comet/stream/extractors/kafka/KafkaExtractorConfiguration$$Defaults$","k":"val"},
{"l":"org/ragna/comet/stream/extractors/kafka/KafkaExtractorConfiguration$$Defaults$.html","n":"defaultSessionTimeout","t":"val defaultSessionTimeout: FiniteDuration","d":"org/ragna/comet/stream/extractors/kafka/KafkaExtractorConfiguration$$Defaults$","k":"val"},
{"l":"org/ragna/comet/stream/extractors/list.html","n":"org.ragna.comet.stream.extractors.list","t":"package org.ragna.comet.stream.extractors.list","d":"org/ragna/comet/stream/extractors/list","k":"package"},
{"l":"org/ragna/comet/stream/extractors/list/ListExtractor.html","n":"ListExtractor","t":"class ListExtractor[A](items: Seq[A], format: DataFormat, inference: InferenceEngine, concurrentItems: Int, itemTimeout: Option[FiniteDuration])(implicit toRdfElement: A => RDFElement) extends StreamExtractor[A]","d":"org/ragna/comet/stream/extractors/list/ListExtractor","k":"class"},
{"l":"org/ragna/comet/stream/extractors/list/ListExtractor.html","n":"source","t":"val source: StreamSource","d":"org/ragna/comet/stream/extractors/list/ListExtractor","k":"val"},
{"l":"org/ragna/comet/trigger.html","n":"org.ragna.comet.trigger","t":"package org.ragna.comet.trigger","d":"org/ragna/comet/trigger","k":"package"},
{"l":"org/ragna/comet/trigger/ShapeMapFormat.html","n":"ShapeMapFormat","t":"class ShapeMapFormat(val name: String)","d":"org/ragna/comet/trigger/ShapeMapFormat","k":"class"},
{"l":"org/ragna/comet/trigger/ShapeMapFormat.html","n":"name","t":"val name: String","d":"org/ragna/comet/trigger/ShapeMapFormat","k":"val"},
{"l":"org/ragna/comet/trigger/ShapeMapFormat$.html","n":"ShapeMapFormat","t":"object ShapeMapFormat","d":"org/ragna/comet/trigger/ShapeMapFormat$","k":"object"},
{"l":"org/ragna/comet/trigger/ShapeMapFormat$$COMPACT$.html","n":"COMPACT","t":"object COMPACT extends ShapeMapFormat","d":"org/ragna/comet/trigger/ShapeMapFormat$$COMPACT$","k":"object"},
{"l":"org/ragna/comet/trigger/ShapeMapFormat$$JSON$.html","n":"JSON","t":"object JSON extends ShapeMapFormat","d":"org/ragna/comet/trigger/ShapeMapFormat$$JSON$","k":"object"},
{"l":"org/ragna/comet/trigger/TriggerModeType.html","n":"TriggerModeType","t":"class TriggerModeType(val name: String)","d":"org/ragna/comet/trigger/TriggerModeType","k":"class"},
{"l":"org/ragna/comet/trigger/TriggerModeType.html","n":"name","t":"val name: String","d":"org/ragna/comet/trigger/TriggerModeType","k":"val"},
{"l":"org/ragna/comet/trigger/TriggerModeType$.html","n":"TriggerModeType","t":"object TriggerModeType","d":"org/ragna/comet/trigger/TriggerModeType$","k":"object"},
{"l":"org/ragna/comet/trigger/TriggerModeType$$SHAPEMAP$.html","n":"SHAPEMAP","t":"object SHAPEMAP extends TriggerModeType","d":"org/ragna/comet/trigger/TriggerModeType$$SHAPEMAP$","k":"object"},
{"l":"org/ragna/comet/trigger/TriggerModeType$$TARGET_DECLARATIONS$.html","n":"TARGET_DECLARATIONS","t":"object TARGET_DECLARATIONS extends TriggerModeType","d":"org/ragna/comet/trigger/TriggerModeType$$TARGET_DECLARATIONS$","k":"object"},
{"l":"org/ragna/comet/trigger/TriggerShapeMap.html","n":"TriggerShapeMap","t":"class TriggerShapeMap(shapeMapText: String, shapeMapFormat: ShapeMapFormat, nodesPrefixMap: PrefixMap, shapesPrefixMap: PrefixMap) extends ValidationTrigger","d":"org/ragna/comet/trigger/TriggerShapeMap","k":"class"},
{"l":"org/ragna/comet/trigger/TriggerShapeMap.html","n":"`type`","t":"val `type`: TriggerModeType","d":"org/ragna/comet/trigger/TriggerShapeMap","k":"val"},
{"l":"org/ragna/comet/trigger/TriggerTargetDeclarations.html","n":"TriggerTargetDeclarations","t":"class TriggerTargetDeclarations() extends ValidationTrigger","d":"org/ragna/comet/trigger/TriggerTargetDeclarations","k":"class"},
{"l":"org/ragna/comet/trigger/TriggerTargetDeclarations.html","n":"`type`","t":"val `type`: TriggerModeType","d":"org/ragna/comet/trigger/TriggerTargetDeclarations","k":"val"},
{"l":"org/ragna/comet/trigger/ValidationTrigger.html","n":"ValidationTrigger","t":"trait ValidationTrigger","d":"org/ragna/comet/trigger/ValidationTrigger","k":"trait"},
{"l":"org/ragna/comet/trigger/ValidationTrigger.html","n":"`type`","t":"val `type`: TriggerModeType","d":"org/ragna/comet/trigger/ValidationTrigger","k":"val"},
{"l":"org/ragna/comet/trigger/ValidationTrigger.html","n":"getValidationTrigger","t":"def getValidationTrigger: Either[List[String], ValidationTrigger]","d":"org/ragna/comet/trigger/ValidationTrigger","k":"def"},
{"l":"org/ragna/comet/utils.html","n":"org.ragna.comet.utils","t":"package org.ragna.comet.utils","d":"org/ragna/comet/utils","k":"package"},
{"l":"org/ragna/comet/utils.html","n":"DurationValidationOps","t":"def DurationValidationOps(duration: FiniteDuration): DurationValidationOps","d":"org/ragna/comet/utils","k":"def"},
{"l":"org/ragna/comet/utils.html","n":"Fs2StreamOps","t":"def Fs2StreamOps[O](stream: Stream[IO, O]): Fs2StreamOps[O]","d":"org/ragna/comet/utils","k":"def"},
{"l":"org/ragna/comet/utils.html","n":"IODebugOps","t":"def IODebugOps[A](io: IO[A]): IODebugOps[A]","d":"org/ragna/comet/utils","k":"def"},
{"l":"org/ragna/comet/utils/DurationValidationOps.html","n":"DurationValidationOps","t":"class DurationValidationOps(duration: FiniteDuration)","d":"org/ragna/comet/utils/DurationValidationOps","k":"class"},
{"l":"org/ragna/comet/utils/DurationValidationOps.html","n":"isBetween","t":"def isBetween(min: FiniteDuration, max: FiniteDuration): Boolean","d":"org/ragna/comet/utils/DurationValidationOps","k":"def"},
{"l":"org/ragna/comet/utils/Fs2StreamOps.html","n":"Fs2StreamOps","t":"class Fs2StreamOps[O](stream: Stream[IO, O]) extends LazyLogging","d":"org/ragna/comet/utils/Fs2StreamOps","k":"class"},
{"l":"org/ragna/comet/utils/Fs2StreamOps.html","n":"timedStream","t":"def timedStream(timeout: FiniteDuration): Stream[IO, O]","d":"org/ragna/comet/utils/Fs2StreamOps","k":"def"},
{"l":"org/ragna/comet/utils/IODebugOps.html","n":"IODebugOps","t":"class IODebugOps[A](io: IO[A])","d":"org/ragna/comet/utils/IODebugOps","k":"class"},
{"l":"org/ragna/comet/utils/IODebugOps.html","n":"debug","t":"def debug: IO[A]","d":"org/ragna/comet/utils/IODebugOps","k":"def"},
{"l":"org/ragna/comet/utils/StreamUtils$.html","n":"StreamUtils","t":"object StreamUtils","d":"org/ragna/comet/utils/StreamUtils$","k":"object"},
{"l":"org/ragna/comet/utils/StreamUtils$.html","n":"toConsole","t":"def toConsole[A]: (IO, A) => A","d":"org/ragna/comet/utils/StreamUtils$","k":"def"},
{"l":"org/ragna/comet/utils/Timer.html","n":"Timer","t":"class Timer[A](action: IO[A], delay: FiniteDuration) extends LazyLogging","d":"org/ragna/comet/utils/Timer","k":"class"},
{"l":"org/ragna/comet/utils/Timer.html","n":"cancel","t":"def cancel(): IO[Unit]","d":"org/ragna/comet/utils/Timer","k":"def"},
{"l":"org/ragna/comet/utils/Timer.html","n":"schedule","t":"def schedule(): IO[Unit]","d":"org/ragna/comet/utils/Timer","k":"def"},
{"l":"org/ragna/comet/validation.html","n":"org.ragna.comet.validation","t":"package org.ragna.comet.validation","d":"org/ragna/comet/validation","k":"package"},
{"l":"org/ragna/comet/validation/Validator.html","n":"Validator","t":"class Validator[A](configuration: ValidatorConfiguration, extractor: StreamExtractor[A]) extends LazyLogging","d":"org/ragna/comet/validation/Validator","k":"class"},
{"l":"org/ragna/comet/validation/Validator.html","n":"dataFormat","t":"val dataFormat: DataFormat","d":"org/ragna/comet/validation/Validator","k":"val"},
{"l":"org/ragna/comet/validation/Validator.html","n":"dataInference","t":"val dataInference: InferenceEngine","d":"org/ragna/comet/validation/Validator","k":"val"},
{"l":"org/ragna/comet/validation/Validator.html","n":"dataSource","t":"val dataSource: StreamSource","d":"org/ragna/comet/validation/Validator","k":"val"},
{"l":"org/ragna/comet/validation/Validator.html","n":"schema","t":"val schema: Schema","d":"org/ragna/comet/validation/Validator","k":"val"},
{"l":"org/ragna/comet/validation/Validator.html","n":"this","t":"def this(extractor: StreamExtractor[A], schema: Schema, trigger: ValidationTrigger)","d":"org/ragna/comet/validation/Validator","k":"def"},
{"l":"org/ragna/comet/validation/Validator.html","n":"validate","t":"def validate: Stream[IO, ValidationResult]","d":"org/ragna/comet/validation/Validator","k":"def"},
{"l":"org/ragna/comet/validation/Validator.html","n":"validationTrigger","t":"val validationTrigger: ValidationTrigger","d":"org/ragna/comet/validation/Validator","k":"val"},
{"l":"org/ragna/comet/validation/configuration.html","n":"org.ragna.comet.validation.configuration","t":"package org.ragna.comet.validation.configuration","d":"org/ragna/comet/validation/configuration","k":"package"},
{"l":"org/ragna/comet/validation/configuration/ValidatorConfiguration.html","n":"ValidatorConfiguration","t":"class ValidatorConfiguration(schema: Schema, trigger: ValidationTrigger, haltOnInvalid: Boolean, haltOnErrored: Boolean, concurrentItems: Int)","d":"org/ragna/comet/validation/configuration/ValidatorConfiguration","k":"class"},
{"l":"org/ragna/comet/validation/configuration/ValidatorConfiguration$.html","n":"ValidatorConfiguration","t":"object ValidatorConfiguration","d":"org/ragna/comet/validation/configuration/ValidatorConfiguration$","k":"object"},
{"l":"org/ragna/comet/validation/configuration/ValidatorConfiguration$$Defaults$.html","n":"Defaults","t":"object Defaults","d":"org/ragna/comet/validation/configuration/ValidatorConfiguration$$Defaults$","k":"object"},
{"l":"org/ragna/comet/validation/configuration/ValidatorConfiguration$$Defaults$.html","n":"defaultConcurrentValidations","t":"val defaultConcurrentValidations: Int","d":"org/ragna/comet/validation/configuration/ValidatorConfiguration$$Defaults$","k":"val"},
{"l":"org/ragna/comet/validation/configuration/ValidatorConfiguration$$Defaults$.html","n":"defaultHaltOnErrored","t":"val defaultHaltOnErrored: Boolean","d":"org/ragna/comet/validation/configuration/ValidatorConfiguration$$Defaults$","k":"val"},
{"l":"org/ragna/comet/validation/configuration/ValidatorConfiguration$$Defaults$.html","n":"defaultHaltOnInvalid","t":"val defaultHaltOnInvalid: Boolean","d":"org/ragna/comet/validation/configuration/ValidatorConfiguration$$Defaults$","k":"val"},
{"l":"org/ragna/comet/validation/result.html","n":"org.ragna.comet.validation.result","t":"package org.ragna.comet.validation.result","d":"org/ragna/comet/validation/result","k":"package"},
{"l":"org/ragna/comet/validation/result/ResultStatus.html","n":"ResultStatus","t":"class ResultStatus(val textValue: String, val valid: Boolean)","d":"org/ragna/comet/validation/result/ResultStatus","k":"class"},
{"l":"org/ragna/comet/validation/result/ResultStatus.html","n":"textValue","t":"val textValue: String","d":"org/ragna/comet/validation/result/ResultStatus","k":"val"},
{"l":"org/ragna/comet/validation/result/ResultStatus.html","n":"valid","t":"val valid: Boolean","d":"org/ragna/comet/validation/result/ResultStatus","k":"val"},
{"l":"org/ragna/comet/validation/result/ResultStatus$.html","n":"ResultStatus","t":"object ResultStatus","d":"org/ragna/comet/validation/result/ResultStatus$","k":"object"},
{"l":"org/ragna/comet/validation/result/ResultStatus$.html","n":"fromValidationReport","t":"def fromValidationReport(report: Option[Result]): ResultStatus","d":"org/ragna/comet/validation/result/ResultStatus$","k":"def"},
{"l":"org/ragna/comet/validation/result/ResultStatus$$ERRORED$.html","n":"ERRORED","t":"object ERRORED extends ResultStatus","d":"org/ragna/comet/validation/result/ResultStatus$$ERRORED$","k":"object"},
{"l":"org/ragna/comet/validation/result/ResultStatus$$INVALID$.html","n":"INVALID","t":"object INVALID extends ResultStatus","d":"org/ragna/comet/validation/result/ResultStatus$$INVALID$","k":"object"},
{"l":"org/ragna/comet/validation/result/ResultStatus$$VALID$.html","n":"VALID","t":"object VALID extends ResultStatus","d":"org/ragna/comet/validation/result/ResultStatus$$VALID$","k":"object"},
{"l":"org/ragna/comet/validation/result/ValidationResult.html","n":"ValidationResult","t":"class ValidationResult(inputResult: Either[Throwable, Result])","d":"org/ragna/comet/validation/result/ValidationResult","k":"class"},
{"l":"org/ragna/comet/validation/result/ValidationResult.html","n":"message","t":"val message: String","d":"org/ragna/comet/validation/result/ValidationResult","k":"val"},
{"l":"org/ragna/comet/validation/result/ValidationResult.html","n":"result","t":"val result: Option[Result]","d":"org/ragna/comet/validation/result/ValidationResult","k":"val"},
{"l":"org/ragna/comet/validation/result/ValidationResult.html","n":"status","t":"val status: ResultStatus","d":"org/ragna/comet/validation/result/ValidationResult","k":"val"},
{"l":"org/ragna/comet/validation/result/ValidationResult$.html","n":"ValidationResult","t":"object ValidationResult","d":"org/ragna/comet/validation/result/ValidationResult$","k":"object"},
{"l":"org/ragna/comet/validation/result/ValidationResult$.html","n":"encoder","t":"val encoder: Encoder[ValidationResult]","d":"org/ragna/comet/validation/result/ValidationResult$","k":"val"},
{"l":"org/ragna/comet/validation/result/ValidationResult$.html","n":"getValidationReportJson","t":"def getValidationReportJson(report: Result): Json","d":"org/ragna/comet/validation/result/ValidationResult$","k":"def"},
{"l":"docs/index.html","n":"comet-api-docs","t":"comet-api-docs","d":"","k":"static"}];