# https://scalameta.org/mdoc/docs/docusaurus.html#publish-to-github-pages-from-ci
# Adapted from https://scalameta.org/mdoc/docs/docusaurus.html#github-actions
name: Publish website (Mdoc + Docusaurus)
on:
  push:
    branches: [ main, master ]
    tags: [ "*" ]
jobs:
  publish:
    name: Build a docusaurus website with guides and scaladoc
    
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
        scala: [ 3.1.2 ]
        java: [ openjdk@1.17.0 ]
    
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Scala
        uses: olafurpg/setup-scala@v13
        with:
          java-version: ${{ matrix.java }}

      - name: Set up GPG
        uses: olafurpg/setup-gpg@v3

      - name: Setup graphviz/dot for scaladoc diagrams
        uses: ts-graphviz/setup-graphviz@v1

      - name: Build and publish docusaurus site, generating the scaladoc
        run: sbt 'docs/docusaurusPublishGhpages'
        env:
          GIT_DEPLOY_KEY: ${{ secrets.COMET_DEPLOY_KEY }}
