name: Publish OSS Sonatype
on:
  push:
    branches: [ master, main ]
    tags: [ "*" ]
jobs:
  publish:
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
        scala: [ 3.1.2 ]
        java: [ openjdk@1.17.0 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: olafurpg/setup-scala@v13
        with:
          java-version: ${{ matrix.java }}
      - run: sbt ++${{ matrix.scala }} ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
